-- Supabase SQL for your current setup
-- Keeps parking_floor1 and parking_floor2
-- Adds user profile, car registration, booking storage
-- Booking is allowed only for floor 2 because floor 2 has the barrier

create extension if not exists "pgcrypto";

-- =========================
-- USER PROFILE
-- =========================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update
    set email = excluded.email;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- =========================
-- YOUR CURRENT FLOOR TABLES
-- =========================

create table if not exists public.parking_floor1 (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  slot int8 not null check (slot between 1 and 3),
  status text not null check (status in ('empty', 'occupied'))
);

create table if not exists public.parking_floor2 (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  slot int8 not null check (slot between 1 and 3),
  status text not null check (status in ('empty', 'occupied'))
);

-- =========================
-- USER CARS
-- =========================

create table if not exists public.vehicle_registrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plate_number text not null,
  created_at timestamptz not null default now(),
  unique (user_id, plate_number)
);

-- =========================
-- USER BOOKINGS
-- =========================

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  vehicle_id uuid not null references public.vehicle_registrations(id) on delete cascade,
  floor_no int not null check (floor_no = 2),
  slot int not null check (slot between 1 and 3),
  start_time timestamptz not null,
  end_time timestamptz not null,
  status text not null default 'booked' check (status in ('booked', 'checked_in', 'completed', 'cancelled', 'expired')),
  created_at timestamptz not null default now(),
  constraint booking_time_valid check (end_time > start_time)
);

create index if not exists idx_vehicle_registrations_user_id
  on public.vehicle_registrations(user_id);

create index if not exists idx_bookings_user_id
  on public.bookings(user_id);

create index if not exists idx_bookings_floor_slot
  on public.bookings(floor_no, slot);

-- =========================
-- OPTIONAL VIEW FOR APP
-- =========================

create or replace view public.booking_overview as
select
  b.id,
  b.user_id,
  p.email,
  v.plate_number,
  b.floor_no,
  b.slot,
  b.start_time,
  b.end_time,
  b.status,
  b.created_at
from public.bookings b
join public.vehicle_registrations v on v.id = b.vehicle_id
left join public.profiles p on p.id = b.user_id;

-- =========================
-- RLS
-- =========================

alter table public.profiles enable row level security;
alter table public.vehicle_registrations enable row level security;
alter table public.bookings enable row level security;
alter table public.parking_floor1 enable row level security;
alter table public.parking_floor2 enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "users_manage_own_vehicles" on public.vehicle_registrations;
create policy "users_manage_own_vehicles"
  on public.vehicle_registrations
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "users_manage_own_bookings" on public.bookings;
create policy "users_manage_own_bookings"
  on public.bookings
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "authenticated_read_floor1" on public.parking_floor1;
create policy "authenticated_read_floor1"
  on public.parking_floor1
  for select
  using (auth.role() = 'authenticated');

drop policy if exists "authenticated_read_floor2" on public.parking_floor2;
create policy "authenticated_read_floor2"
  on public.parking_floor2
  for select
  using (auth.role() = 'authenticated');

-- =========================
-- HELPER FUNCTION TO CREATE BOOKING
-- =========================

create or replace function public.create_booking(
  p_vehicle_id uuid,
  p_floor_no int,
  p_slot int,
  p_start_time timestamptz,
  p_end_time timestamptz
)
returns public.bookings
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_owner uuid;
  v_booking public.bookings;
  v_conflict_count int;
begin
  if v_user_id is null then
    raise exception 'AUTH_REQUIRED' using errcode = 'P0001';
  end if;

  if p_end_time <= p_start_time then
    raise exception 'INVALID_TIME_RANGE' using errcode = 'P0001';
  end if;

  if p_floor_no <> 2 then
    raise exception 'BOOKING_ALLOWED_ONLY_FOR_FLOOR_2' using errcode = 'P0001';
  end if;

  if p_start_time <= now() then
    raise exception 'START_TIME_MUST_BE_IN_THE_FUTURE' using errcode = 'P0001';
  end if;

  select user_id into v_owner
  from public.vehicle_registrations
  where id = p_vehicle_id;

  if v_owner is distinct from v_user_id then
    raise exception 'VEHICLE_NOT_OWNED_BY_USER' using errcode = 'P0001';
  end if;

  select count(*)
  into v_conflict_count
  from public.bookings
  where floor_no = p_floor_no
    and slot = p_slot
    and status in ('booked', 'checked_in')
    and p_start_time < end_time
    and p_end_time > start_time;

  if v_conflict_count > 0 then
    raise exception 'SLOT_ALREADY_BOOKED' using errcode = 'P0001';
  end if;

  insert into public.bookings (
    user_id,
    vehicle_id,
    floor_no,
    slot,
    start_time,
    end_time
  )
  values (
    v_user_id,
    p_vehicle_id,
    p_floor_no,
    p_slot,
    p_start_time,
    p_end_time
  )
  returning * into v_booking;

  return v_booking;
end;
$$;

grant execute on function public.create_booking(uuid, int, int, timestamptz, timestamptz)
  to authenticated;

-- =========================
-- BARRIER / CAMERA VALIDATION
-- Camera sends plate number + current floor/slot
-- Barrier opens only if:
-- 1. plate belongs to a user
-- 2. booking is on floor 2
-- 3. slot matches
-- 4. current time is inside booking window
-- =========================

create or replace function public.validate_barrier_entry(
  p_plate_number text,
  p_floor_no int,
  p_slot int,
  p_check_time timestamptz default now()
)
returns table (
  allowed boolean,
  reason text,
  booking_id uuid,
  user_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booking public.bookings;
begin
  if p_floor_no <> 2 then
    return query select false, 'BARRIER_ONLY_FOR_FLOOR_2', null::uuid, null::uuid;
    return;
  end if;

  select b.*
  into v_booking
  from public.bookings b
  join public.vehicle_registrations v on v.id = b.vehicle_id
  where upper(v.plate_number) = upper(trim(p_plate_number))
    and b.floor_no = p_floor_no
    and b.slot = p_slot
    and b.status in ('booked', 'checked_in')
    and p_check_time >= b.start_time
    and p_check_time <= b.end_time
  order by b.start_time asc
  limit 1;

  if not found then
    return query select false, 'NO_VALID_BOOKING', null::uuid, null::uuid;
    return;
  end if;

  if v_booking.status = 'booked' then
    update public.bookings
    set status = 'checked_in'
    where id = v_booking.id;
  end if;

  return query select true, 'ALLOW', v_booking.id, v_booking.user_id;
end;
$$;

-- =========================
-- SAMPLE INSERTS FOR FLOOR STATUS
-- =========================
-- insert into public.parking_floor1 (slot, status) values (1, 'empty'), (2, 'empty'), (3, 'occupied');
-- insert into public.parking_floor2 (slot, status) values (1, 'empty'), (2, 'occupied'), (3, 'empty');
