-- EZP Smart Parking schema
-- Purpose:
-- 1. Register users with Supabase Auth
-- 2. Store each user's cars
-- 3. Let users book a parking slot for a time range
-- 4. Keep parking slot structure separate from sensor/event data

create extension if not exists "pgcrypto";
create extension if not exists "btree_gist";

-- Optional cleanup if you want to replace the old raw tables from the screenshot.
drop table if exists public.parking_floor1;
drop table if exists public.parking_floor2;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'booking_status') then
    create type public.booking_status as enum (
      'booked',
      'checked_in',
      'completed',
      'cancelled',
      'expired'
    );
  end if;
end
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.parking_floors (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.parking_slots (
  id bigint generated by default as identity primary key,
  floor_id bigint not null references public.parking_floors(id) on delete cascade,
  code text not null unique,
  slot_number int not null,
  is_reservable boolean not null default true,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (floor_id, slot_number)
);

create table if not exists public.vehicle_registrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plate_number text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  constraint vehicle_plate_format check (char_length(trim(plate_number)) >= 3),
  unique (user_id, plate_number)
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  vehicle_id uuid not null references public.vehicle_registrations(id) on delete cascade,
  slot_id bigint not null references public.parking_slots(id) on delete cascade,
  start_time timestamptz not null,
  end_time timestamptz not null,
  status public.booking_status not null default 'booked',
  created_at timestamptz not null default now(),
  constraint booking_time_valid check (end_time > start_time)
);

create table if not exists public.parking_events (
  id bigint generated by default as identity primary key,
  slot_id bigint not null references public.parking_slots(id) on delete cascade,
  event_type text not null check (event_type in ('enter', 'exit', 'sensor_update')),
  event_status text,
  created_at timestamptz not null default now()
);

create index if not exists idx_vehicle_registrations_user_id
  on public.vehicle_registrations(user_id);

create index if not exists idx_bookings_user_id
  on public.bookings(user_id);

create index if not exists idx_bookings_slot_id
  on public.bookings(slot_id);

create index if not exists idx_bookings_time_range
  on public.bookings(start_time, end_time);

alter table public.bookings
  drop constraint if exists bookings_no_overlap;

alter table public.bookings
  add constraint bookings_no_overlap
  exclude using gist (
    slot_id with =,
    tstzrange(start_time, end_time, '[)') with &&
  )
  where (status in ('booked', 'checked_in'));

insert into public.parking_floors (code, name)
values
  ('F1', 'Floor 1'),
  ('F2', 'Floor 2')
on conflict (code) do nothing;

insert into public.parking_slots (floor_id, code, slot_number, is_reservable)
select f.id, x.code, x.slot_number, true
from public.parking_floors f
join (
  values
    ('F1', 'F1-S01', 1),
    ('F1', 'F1-S02', 2),
    ('F1', 'F1-S03', 3),
    ('F2', 'F2-S01', 1),
    ('F2', 'F2-S02', 2),
    ('F2', 'F2-S03', 3)
) as x(floor_code, code, slot_number)
  on x.floor_code = f.code
on conflict (code) do nothing;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.create_booking(
  p_vehicle_id uuid,
  p_slot_id bigint,
  p_start_time timestamptz,
  p_end_time timestamptz
)
returns public.bookings
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_booking public.bookings;
  v_vehicle_owner uuid;
  v_slot_reservable boolean;
begin
  if v_user_id is null then
    raise exception 'AUTH_REQUIRED' using errcode = 'P0001';
  end if;

  if p_end_time <= p_start_time then
    raise exception 'INVALID_TIME_RANGE' using errcode = 'P0001';
  end if;

  select user_id into v_vehicle_owner
  from public.vehicle_registrations
  where id = p_vehicle_id;

  if v_vehicle_owner is distinct from v_user_id then
    raise exception 'VEHICLE_NOT_OWNED_BY_USER' using errcode = 'P0001';
  end if;

  select is_reservable into v_slot_reservable
  from public.parking_slots
  where id = p_slot_id
    and is_active = true;

  if v_slot_reservable is not true then
    raise exception 'SLOT_NOT_AVAILABLE_FOR_BOOKING' using errcode = 'P0001';
  end if;

  insert into public.bookings (
    user_id,
    vehicle_id,
    slot_id,
    start_time,
    end_time
  )
  values (
    v_user_id,
    p_vehicle_id,
    p_slot_id,
    p_start_time,
    p_end_time
  )
  returning * into v_booking;

  return v_booking;
exception
  when exclusion_violation then
    raise exception 'SLOT_ALREADY_BOOKED' using errcode = 'P0001';
end;
$$;

grant execute on function public.create_booking(uuid, bigint, timestamptz, timestamptz)
  to authenticated;

alter table public.profiles enable row level security;
alter table public.parking_floors enable row level security;
alter table public.parking_slots enable row level security;
alter table public.vehicle_registrations enable row level security;
alter table public.bookings enable row level security;
alter table public.parking_events enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles
  for select
  using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "public_read_floors" on public.parking_floors;
create policy "public_read_floors"
  on public.parking_floors
  for select
  using (true);

drop policy if exists "public_read_slots" on public.parking_slots;
create policy "public_read_slots"
  on public.parking_slots
  for select
  using (true);

drop policy if exists "users_manage_own_vehicles" on public.vehicle_registrations;
create policy "users_manage_own_vehicles"
  on public.vehicle_registrations
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "users_manage_own_bookings" on public.bookings;
create policy "users_manage_own_bookings"
  on public.bookings
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "authenticated_read_events" on public.parking_events;
create policy "authenticated_read_events"
  on public.parking_events
  for select
  using (auth.role() = 'authenticated');

create or replace view public.booking_overview as
select
  b.id,
  b.user_id,
  v.plate_number,
  s.code as slot_code,
  f.code as floor_code,
  f.name as floor_name,
  b.start_time,
  b.end_time,
  b.status,
  b.created_at
from public.bookings b
join public.vehicle_registrations v on v.id = b.vehicle_id
join public.parking_slots s on s.id = b.slot_id
join public.parking_floors f on f.id = s.floor_id;
